export const CHANGE_INFORMATION = "CHANGE_INFORMATION";
export const SAVE_INFORMATION = "SAVE_INFORMATION";
export const SAVE_DRAFT = "SAVE_DRAFT";
export const SET_CREATE_STEP = "SET_CREATE_STEP";
export const CLEAR_INFORMATION = "CLEAR_INFORMATION";